//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/30/2025 10:20:40
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Products
{
    public partial class Product {

        public Product()
        {
            OnCreated();
        }

        public int ProductID { get; set; }

        public string ProductName { get; set; }

        public int? CategoryID { get; set; }

        public decimal? UnitPrice { get; set; }

        public short? UnitsInStock { get; set; }

        public bool? Discontinued { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
